import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxxl + SPACING.lg,
    borderBottomLeftRadius: RADIUS.xxl,
    borderBottomRightRadius: RADIUS.xxl,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: colors.white,
  },
  headerLinkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  headerLinkText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.white,
  },
  employeeCard: {
    marginTop: -SPACING.xxxl - SPACING.md,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    ...SHADOW.card,
  },
  employeeLeft: {
    flex: 1,
    flexDirection: 'row',
    gap: SPACING.md,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  employeeInfo: {
    flex: 1,
  },
  employeeName: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  roleBadge: {
    marginTop: SPACING.xs,
    alignSelf: 'flex-start',
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
    backgroundColor: '#EEF7FF',
  },
  roleBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
  },
  employeeMeta: {
    marginTop: SPACING.xs,
    fontSize: 12,
    color: colors.textSecondary,
  },
  periodDivider: {
    width: 1,
    marginHorizontal: SPACING.md,
    backgroundColor: colors.border,
  },
  periodBlock: {
    alignItems: 'flex-start',
  },
  periodLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  periodLabel: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  periodValue: {
    marginTop: 2,
    fontSize: 20,
    fontWeight: '800',
    color: colors.primary,
  },
  periodRange: {
    marginTop: 2,
    fontSize: 11,
    color: colors.textSecondary,
  },
  summaryCard: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.primary,
  },
  summaryCol: {
    flex: 1,
  },
  summaryDivider: {
    width: 1,
    marginHorizontal: SPACING.lg,
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  summaryLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  summaryIconWrapper: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  summaryLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.85)',
    letterSpacing: 0.3,
  },
  summaryValue: {
    marginTop: SPACING.sm,
    fontSize: 20,
    fontWeight: '800',
    color: colors.white,
  },
  summaryHint: {
    marginTop: 2,
    fontSize: 11,
    color: 'rgba(255,255,255,0.8)',
  },
  statsRow: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  statCard: {
    flex: 1,
    alignItems: 'center',
    gap: SPACING.xs,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  statIconWrapper: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statLabel: {
    fontSize: 10,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  statValue: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  sectionCard: {
    marginTop: SPACING.xl,
    marginHorizontal: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  sectionTitleIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.primary,
    letterSpacing: 0.3,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: SPACING.sm,
  },
  itemLabel: {
    fontSize: 13,
    color: colors.textPrimary,
  },
  itemValue: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  itemDivider: {
    marginTop: SPACING.xs,
    marginBottom: SPACING.sm,
    height: 1,
    borderStyle: 'dashed',
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  totalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  totalLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.primary,
    letterSpacing: 0.3,
  },
  totalValue: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.primary,
  },
  totalValueDanger: {
    color: '#DC2626',
  },
  netPayBanner: {
    marginTop: SPACING.xl,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: '#EEF7FF',
  },
  netPayIconWrapper: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.6)',
  },
  netPayInfo: {
    flex: 1,
    marginLeft: SPACING.md,
  },
  netPayLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
    letterSpacing: 0.3,
  },
  netPayValue: {
    marginTop: 2,
    fontSize: 22,
    fontWeight: '800',
    color: colors.primary,
  },
  netPayWords: {
    marginTop: 4,
    fontSize: 11,
    fontStyle: 'italic',
    color: colors.textSecondary,
  },
  stampWrapper: {
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 2,
    borderColor: '#2563EB',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-14deg' }],
  },
  stampText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#2563EB',
    textAlign: 'center',
    lineHeight: 12,
  },
  stampTextMain: {
    fontSize: 11,
    fontWeight: '800',
    color: '#2563EB',
  },
  noteBanner: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.sm,
    backgroundColor: '#EEF7FF',
  },
  noteText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 17,
    color: colors.textSecondary,
  },
  noteTextTitle: {
    fontWeight: '700',
    color: colors.primary,
  },
  shareBtn: {
    marginTop: SPACING.xl,
    marginHorizontal: SPACING.xl,
    marginBottom: SPACING.xl,
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.primary,
  },
  shareBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.white,
  },
});
