import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxxl + SPACING.md,
    borderBottomLeftRadius: RADIUS.xxl,
    borderBottomRightRadius: RADIUS.xxl,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: colors.white,
  },
  infoCard: {
    marginTop: -SPACING.xxxl,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  infoImageWrapper: {
    width: 110,
    height: 130,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoImageSpeakerBtn: {
    position: 'absolute',
    right: 6,
    bottom: 6,
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  infoCol: {
    flex: 1,
    marginLeft: SPACING.md,
  },
  wordRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  wordText: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  wordBadgesCol: {
    marginLeft: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  levelBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 3,
    borderRadius: RADIUS.xs,
    backgroundColor: colors.primary,
  },
  levelBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.white,
  },
  phoneticText: {
    marginTop: SPACING.sm,
    fontSize: 14,
    color: colors.textSecondary,
    fontStyle: 'italic',
  },
  meaningText: {
    marginTop: 4,
    fontSize: 18,
    fontWeight: '800',
    color: colors.primary,
  },
  topicTag: {
    marginTop: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-start',
    paddingHorizontal: SPACING.sm,
    paddingVertical: 3,
    borderRadius: RADIUS.xs,
  },
  topicTagText: {
    fontSize: 11,
    fontWeight: '700',
  },
  exampleCard: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: '#FFFBEB',
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  exampleIconWrapper: {
    marginTop: 2,
  },
  exampleCol: {
    flex: 1,
  },
  exampleLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  exampleText: {
    marginTop: 4,
    fontSize: 14,
    color: colors.textPrimary,
  },
  exampleHighlight: {
    color: colors.primary,
    fontWeight: '800',
  },
  exampleTranslation: {
    marginTop: 2,
    fontSize: 13,
    color: colors.textSecondary,
  },
  exampleSpeakerBtn: {
    marginTop: 2,
  },
  actionsGrid: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  actionBtn: {
    flexBasis: '47%',
    flexGrow: 1,
    alignItems: 'center',
    gap: 6,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  actionBtnDisabled: {
    opacity: 0.5,
  },
  actionBtnText: {
    fontSize: 12,
    fontWeight: '700',
  },
  sectionCard: {
    marginTop: SPACING.xl,
    marginHorizontal: SPACING.xl,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  infoRow: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  infoRowIconWrapper: {
    width: 32,
    height: 32,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  infoRowLabel: {
    flex: 1,
    marginLeft: SPACING.sm,
    fontSize: 13,
    color: colors.textPrimary,
  },
  infoRowValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  infoRowValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  infoRowValueMuted: {
    color: colors.textSecondary,
    fontWeight: '600',
  },
  extraExampleRow: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.sm,
  },
  extraExampleSpeakerBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  extraExampleCol: {
    flex: 1,
  },
  extraExampleText: {
    fontSize: 13,
    color: colors.textPrimary,
  },
  extraExampleTranslation: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textSecondary,
  },
  extraExampleActionsCol: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  bottomBar: {
    flexDirection: 'row',
    gap: SPACING.sm,
    paddingHorizontal: SPACING.xl,
    paddingVertical: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.white,
  },
  bottomOutlineBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    height: 46,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.white,
  },
  bottomOutlineBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  bottomPrimaryBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    height: 46,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.primary,
  },
  bottomPrimaryBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.white,
  },
  notFoundWrapper: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.md,
  },
  notFoundText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
});
