import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    padding: SPACING.xl,
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.lg,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: colors.white,
  },
  headerLinkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  headerLinkText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.white,
  },
  themeRow: {
    flexDirection: 'row',
    gap: SPACING.md,
  },
  themeChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1.5,
    backgroundColor: colors.white,
    borderColor: colors.border,
  },
  themeChipIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  themeChipLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  themeChipRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  themeChipRadioActive: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  slipCard: {
    marginTop: SPACING.lg,
    padding: SPACING.xl,
    borderRadius: RADIUS.lg,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    ...SHADOW.card,
  },
  slipHeader: {
    alignItems: 'center',
  },
  serverImageCard: {
    marginTop: SPACING.lg,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  serverImageHeaderRow: {
    marginBottom: SPACING.sm,
  },
  serverImageTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  serverImageLink: {
    marginTop: 2,
    fontSize: 11,
    color: colors.textSecondary,
  },
  serverImagePreview: {
    width: '100%',
    height: 160,
    borderRadius: RADIUS.sm,
    backgroundColor: '#F1F5F9',
  },
  serverImageErrorBox: {
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.xs,
    borderRadius: RADIUS.sm,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.border,
  },
  serverImageErrorText: {
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  slipBrand: {
    fontSize: 30,
    fontWeight: '800',
  },
  slipBrandSub: {
    marginTop: -4,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 2,
    color: colors.textSecondary,
  },
  slipTagline: {
    marginTop: 4,
    fontSize: 10,
    color: colors.textSecondary,
  },
  slipTitleBanner: {
    marginTop: SPACING.lg,
    alignSelf: 'center',
    paddingHorizontal: SPACING.xl,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.sm,
  },
  slipTitleText: {
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 1,
  },
  monthPill: {
    marginTop: SPACING.md,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.xs,
    borderRadius: 999,
    borderWidth: 1,
  },
  monthPillText: {
    fontSize: 13,
    fontWeight: '700',
  },
  slipFieldsWrapper: {
    marginTop: SPACING.xl,
    gap: SPACING.lg,
  },
  slipFieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  slipFieldIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  slipFieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  slipFieldInput: {
    flex: 1,
    fontSize: 13,
    color: colors.textPrimary,
    borderBottomWidth: 1,
    borderStyle: 'dotted',
    paddingVertical: 2,
    paddingLeft: SPACING.xs,
  },
  slipFieldValue: {
    flex: 1,
    fontSize: 13,
    color: colors.textPrimary,
    paddingLeft: SPACING.xs,
  },
  slipFieldPlaceholder: {
    color: colors.textSecondary,
  },
  slipAttendanceInput: {
    marginLeft: 38,
    fontSize: 13,
    color: colors.textPrimary,
    borderBottomWidth: 1,
    borderStyle: 'dotted',
    minHeight: 40,
    textAlignVertical: 'top',
    paddingVertical: 2,
  },
  remarkBox: {
    marginTop: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderStyle: 'dashed',
  },
  remarkHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  remarkHeaderIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  remarkHeaderText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
  },
  remarkFieldLabel: {
    marginTop: SPACING.md,
    fontSize: 12,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  remarkFieldInput: {
    marginTop: 4,
    fontSize: 12,
    color: colors.textPrimary,
    borderBottomWidth: 1,
    borderStyle: 'dotted',
    minHeight: 40,
    textAlignVertical: 'top',
    paddingVertical: 2,
  },
  studentPickerBtn: {
    flex: 1,
  },
  actionsWrapper: {
    marginTop: SPACING.xl,
    gap: SPACING.md,
  },
  actionsRow: {
    flexDirection: 'row',
    gap: SPACING.md,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    height: 48,
    borderRadius: RADIUS.sm,
    borderWidth: 1.5,
  },
  actionBtnPrimary: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  actionBtnOutline: {
    backgroundColor: colors.white,
    borderColor: colors.primary,
  },
  actionBtnGreen: {
    backgroundColor: colors.white,
    borderColor: '#16A34A',
  },
  actionBtnZalo: {
    backgroundColor: colors.white,
    borderColor: '#2563EB',
  },
  actionBtnDisabled: {
    opacity: 0.5,
  },
  actionBtnText: {
    fontSize: 14,
    fontWeight: '700',
  },
  securityBanner: {
    marginTop: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.sm,
    backgroundColor: '#EEF7FF',
  },
  securityText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 16,
    color: colors.textSecondary,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.5)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    padding: SPACING.xl,
    maxHeight: '75%',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: SPACING.md,
  },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  modalOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  modalOptionText: {
    fontSize: 14,
    color: colors.textPrimary,
  },
  modalOptionTextActive: {
    fontWeight: '700',
    color: colors.primary,
  },
  searchInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    height: 46,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.white,
    paddingHorizontal: SPACING.md,
    marginBottom: SPACING.md,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: colors.textPrimary,
    padding: 0,
  },
  studentPickRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  initialsAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  initialsText: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.white,
  },
  studentPickName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  loadingWrapper: {
    paddingVertical: SPACING.xxl,
  },
  emptyText: {
    marginTop: SPACING.md,
    textAlign: 'center',
    fontSize: 13,
    color: colors.textSecondary,
  },
});
