packages:
  - 'agents/*'
  - 'apps/*'
  - 'webs/*'
  - 'packages/*'
  - 'services/*'

allowBuilds:
  esbuild: false

catalog:
  "@hookform/resolvers": "3.10.0"
  "@types/lodash": "4.17.24"
  # Phải khớp với React bản 19.1.0
  "@types/react": "19.1.0" 
  "@types/react-native": "0.73.0"

  # Utilities
  axios: "1.14.0"
  lodash: "4.18.1"

  # State Management & Form
  mobx: "6.15.0"
  mobx-persist-store: "1.1.8"
  mobx-react: "9.2.1"
  mobx-react-lite: "4.1.1"
  moment: "2.30.1"

  # React Ecosystem - ĐÃ FIX VERSION CHO EXPO 54
  react: "19.1.0"
  react-dom: "19.1.0"
  react-hook-form: "7.72.0"
  
  socket.io-client: "2.5.0"
  typescript: "5.9.3"
  yup: "1.7.1"

  # Validation
  zod: "4.3.6"