import { Dimensions, StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
export const CARD_WIDTH = SCREEN_WIDTH - SPACING.xl * 2 - SPACING.xxl * 2;
export const CARD_SPACING = SPACING.md;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxl,
    borderBottomLeftRadius: RADIUS.xxl,
    borderBottomRightRadius: RADIUS.xxl,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '700',
    color: colors.white,
  },
  promoCard: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  promoIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  promoTextWrapper: {
    flex: 1,
  },
  promoTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.white,
  },
  promoDesc: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 17,
    color: 'rgba(255,255,255,0.85)',
  },
  section: {
    paddingHorizontal: SPACING.xl,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: SPACING.sm,
  },
  currentCard: {
    marginTop: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  currentLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  currentTopRow: {
    marginTop: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
  },
  currentBadgeIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  currentInfo: {
    flex: 1,
  },
  currentName: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  currentExpiryChip: {
    marginTop: SPACING.xs,
    alignSelf: 'flex-start',
    paddingHorizontal: SPACING.md,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#F1F5F9',
  },
  currentExpiryText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  currentUpgradeBtn: {
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.xs,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  currentUpgradeBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  cycleRow: {
    marginTop: SPACING.xl,
    flexDirection: 'row',
    gap: SPACING.md,
  },
  cycleOption: {
    flex: 1,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.sm,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  cycleOptionActive: {
    borderColor: colors.primary,
    backgroundColor: '#EEF7FF',
  },
  cycleOptionLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  cycleOptionBadge: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: '600',
    color: '#16A34A',
  },
  cycleCheckBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.white,
  },
  carouselWrapper: {
    marginTop: SPACING.xl,
  },
  carouselContent: {
    paddingHorizontal: SPACING.xl,
    gap: CARD_SPACING,
  },
  tierCard: {
    width: CARD_WIDTH,
    borderRadius: RADIUS.xl,
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.border,
    overflow: 'hidden',
    ...SHADOW.card,
  },
  tierCardActive: {
    borderColor: colors.primary,
  },
  tierBadgeRow: {
    alignItems: 'center',
    paddingTop: SPACING.md,
  },
  tierBadge: {
    paddingHorizontal: SPACING.md,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: colors.primary,
  },
  tierBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.white,
  },
  tierHeader: {
    alignItems: 'center',
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.lg,
  },
  tierIconWrapper: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: SPACING.sm,
  },
  tierName: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  tierDesc: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  tierPrice: {
    marginTop: SPACING.md,
    fontSize: 26,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  tierPriceSuffix: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  tierCtaBtn: {
    marginHorizontal: SPACING.lg,
    height: 46,
    justifyContent: 'center',
    borderRadius: RADIUS.sm,
    backgroundColor: colors.primary,
  },
  tierCtaBtnOutline: {
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  tierCtaBtnDisabled: {
    backgroundColor: '#F1F5F9',
  },
  tierCtaBtnText: {
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '700',
    color: colors.white,
  },
  tierCtaBtnTextOutline: {
    color: colors.primary,
  },
  tierCtaBtnTextDisabled: {
    color: colors.textSecondary,
  },
  tierFeatureList: {
    marginTop: SPACING.lg,
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.lg,
    gap: SPACING.sm,
  },
  tierFeatureRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.sm,
  },
  tierFeatureIconWrapper: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DCFCE7',
    marginTop: 1,
  },
  tierFeatureText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    color: colors.textPrimary,
  },
  dotsRow: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: SPACING.xs,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.border,
  },
  dotActive: {
    width: 18,
    backgroundColor: colors.primary,
  },
  infoBanner: {
    marginTop: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.md,
    padding: SPACING.lg,
    borderRadius: RADIUS.md,
    backgroundColor: '#EEF7FF',
  },
  infoIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  infoTextWrapper: {
    flex: 1,
  },
  infoTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  infoDesc: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 17,
    color: colors.textSecondary,
  },
  termsSection: {
    marginTop: SPACING.xl,
  },
  termRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  termText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    color: colors.textSecondary,
  },
  loadingWrapper: {
    paddingVertical: SPACING.xxl,
  },
  bottomBar: {
    paddingHorizontal: SPACING.xl,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.xl,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    ...SHADOW.card,
  },
  submitButton: {
    height: 52,
    justifyContent: 'center',
    borderRadius: RADIUS.sm,
    backgroundColor: colors.primary,
  },
  submitButtonDisabled: {
    opacity: 0.5,
  },
  submitButtonText: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '700',
    color: colors.white,
  },
});
