import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxl,
    borderBottomLeftRadius: RADIUS.xxl,
    borderBottomRightRadius: RADIUS.xxl,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: colors.white,
  },
  headerAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  headerAddBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.white,
  },
  searchRow: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  searchInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    height: 46,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.white,
    paddingHorizontal: SPACING.md,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: colors.textPrimary,
    padding: 0,
  },
  filterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    height: 46,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.white,
  },
  filterBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  statsCard: {
    marginTop: -SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    padding: SPACING.md,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
    gap: 6,
  },
  statItemDivider: {
    borderLeftWidth: 1,
    borderLeftColor: colors.border,
  },
  statIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statValue: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  statLabel: {
    fontSize: 10,
    color: colors.textSecondary,
  },
  tabsRow: {
    marginTop: SPACING.xl,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    paddingBottom: SPACING.sm,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabItemActive: {
    borderBottomColor: colors.primary,
  },
  tabItemText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  tabItemTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  sortViewRow: {
    marginTop: SPACING.md,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sortBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  sortLabel: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  sortValue: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
  viewToggleRow: {
    flexDirection: 'row',
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  viewToggleBtn: {
    width: 34,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  viewToggleBtnActive: {
    backgroundColor: '#EEF7FF',
  },
  listWrapper: {
    marginTop: SPACING.md,
    marginHorizontal: SPACING.xl,
  },
  vocabCard: {
    flexDirection: 'row',
    padding: SPACING.md,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: SPACING.md,
    ...SHADOW.card,
  },
  vocabImageWrapper: {
    width: 84,
    height: 96,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vocabInfo: {
    flex: 1,
    marginLeft: SPACING.md,
  },
  vocabTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  vocabWord: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  vocabSpeakerBtn: {
    padding: 2,
  },
  vocabBadgesCol: {
    marginLeft: 'auto',
    alignItems: 'flex-end',
    gap: SPACING.xs,
  },
  levelBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
    backgroundColor: colors.primary,
  },
  levelBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.white,
  },
  vocabPhonetic: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textSecondary,
    fontStyle: 'italic',
  },
  vocabMeaning: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  vocabExample: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textSecondary,
  },
  vocabExampleHighlight: {
    color: colors.primary,
    fontWeight: '700',
  },
  topicTag: {
    marginTop: SPACING.xs,
    alignSelf: 'flex-start',
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
  },
  topicTagText: {
    fontSize: 10,
    fontWeight: '700',
  },
  vocabActionsRow: {
    marginTop: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.lg,
  },
  vocabActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  vocabActionBtnText: {
    fontSize: 12,
    fontWeight: '700',
  },
  vocabMoreBtn: {
    marginLeft: 'auto',
    padding: 2,
  },
  gridWrapper: {
    marginTop: SPACING.md,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.md,
  },
  gridCard: {
    flexBasis: '47%',
    flexGrow: 1,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    ...SHADOW.card,
  },
  gridImageWrapper: {
    height: 90,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridStarBtn: {
    position: 'absolute',
    top: 6,
    right: 6,
  },
  gridLevelBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
    backgroundColor: colors.primary,
  },
  gridLevelBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: colors.white,
  },
  gridInfo: {
    padding: SPACING.sm,
  },
  gridWord: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  gridMeaning: {
    marginTop: 1,
    fontSize: 11,
    color: colors.textSecondary,
  },
  paginationText: {
    marginTop: SPACING.md,
    textAlign: 'center',
    fontSize: 12,
    color: colors.textSecondary,
  },
  emptyWrapper: {
    marginTop: SPACING.xl,
    marginHorizontal: SPACING.xl,
    alignItems: 'center',
    paddingVertical: SPACING.xxl,
  },
  emptyText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  floatingAddBtn: {
    position: 'absolute',
    right: SPACING.xl,
    bottom: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.xxl,
    backgroundColor: colors.primary,
    ...SHADOW.card,
  },
  floatingAddBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.white,
  },
});
