import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    padding: SPACING.xl,
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.lg,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '700',
    color: colors.white,
  },
  headerHelpBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  headerHelpText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.white,
  },
  stepperCard: {
    marginTop: -SPACING.md,
    marginHorizontal: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    ...SHADOW.card,
  },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stepCircleWrapper: {
    alignItems: 'center',
    width: 64,
  },
  stepCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  stepCircleActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  stepCircleText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  stepCircleTextActive: {
    color: colors.white,
  },
  stepLabel: {
    marginTop: SPACING.xs,
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
    textAlign: 'center',
  },
  stepLabelActive: {
    color: colors.primary,
  },
  stepLine: {
    flex: 1,
    height: 2,
    backgroundColor: colors.border,
    marginBottom: 18,
  },
  stepLineActive: {
    backgroundColor: colors.primary,
  },
  sectionCard: {
    marginTop: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: SPACING.md,
  },
  packageTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
  },
  packageIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  packageInfo: {
    flex: 1,
  },
  packageNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  packageName: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  packageBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
    backgroundColor: colors.primary,
  },
  packageBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.white,
  },
  packageDesc: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textSecondary,
  },
  featureChipsRow: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  featureChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#F1F5F9',
  },
  featureChipIcon: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  featureChipText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  infoRow: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  infoRowFirst: {
    marginTop: SPACING.lg,
    borderTopWidth: 0,
    paddingTop: 0,
  },
  infoRowLabel: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  infoRowValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  infoRowValuePrimary: {
    color: colors.primary,
  },
  changePlanBtn: {
    marginTop: SPACING.lg,
    height: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.xs,
    borderRadius: RADIUS.sm,
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  changePlanBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  savingsBanner: {
    marginTop: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.sm,
    backgroundColor: '#EEF7FF',
  },
  savingsTextWrapper: {
    flex: 1,
  },
  savingsTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  savingsToggleLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  orderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SPACING.md,
  },
  orderLabel: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  orderValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  orderCycleChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: SPACING.md,
    paddingVertical: 6,
    borderRadius: RADIUS.xs,
    backgroundColor: '#EEF7FF',
  },
  orderCycleChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  orderDiscountValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#16A34A',
  },
  orderDivider: {
    marginVertical: SPACING.sm,
    height: 1,
    backgroundColor: '#F1F5F9',
  },
  orderTotalLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  orderTotalValue: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.primary,
  },
  paymentSection: {
    marginTop: SPACING.xl,
  },
  paymentGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.md,
  },
  paymentCard: {
    width: '47%',
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  paymentCardActive: {
    borderColor: colors.primary,
    backgroundColor: '#F8FBFF',
  },
  paymentCardTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  paymentIcon: {
    width: 32,
    height: 32,
    borderRadius: RADIUS.xs,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterActive: {
    borderColor: colors.primary,
  },
  radioInner: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: colors.primary,
  },
  paymentTitle: {
    marginTop: SPACING.sm,
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  paymentDesc: {
    marginTop: 2,
    fontSize: 11,
    color: colors.textSecondary,
  },
  securityBanner: {
    marginTop: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.sm,
    backgroundColor: '#DCFCE7',
  },
  securityBannerText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    color: '#16A34A',
  },
  loadingWrapper: {
    paddingVertical: SPACING.xxl,
  },
  bottomBar: {
    paddingHorizontal: SPACING.xl,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.lg,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    ...SHADOW.card,
  },
  submitButton: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.primary,
  },
  submitButtonDisabled: {
    opacity: 0.5,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.white,
  },
  guaranteeRow: {
    marginTop: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  guaranteeText: {
    fontSize: 11,
    color: colors.textSecondary,
    textAlign: 'center',
  },
});
