import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    paddingBottom: SPACING.xxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxl,
    borderBottomLeftRadius: RADIUS.xxl,
    borderBottomRightRadius: RADIUS.xxl,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerIconBtnHidden: {
    opacity: 0,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '700',
    color: colors.white,
  },
  stepperCard: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  stepItem: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  stepDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E2E8F0',
  },
  stepDotActive: {
    backgroundColor: colors.primary,
  },
  stepDotDone: {
    backgroundColor: '#16A34A',
  },
  stepDotText: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.textSecondary,
  },
  stepDotTextActive: {
    color: colors.white,
  },
  stepLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSecondary,
    textAlign: 'center',
  },
  stepLabelActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  stepLabelDone: {
    color: '#16A34A',
    fontWeight: '700',
  },
  stepSeparator: {
    width: 12,
    marginTop: 11,
  },
  sectionCard: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
  },
  thumbnailWrapper: {
    height: 120,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  gameTitle: {
    marginTop: SPACING.md,
    fontSize: 16,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  metaRow: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    paddingVertical: SPACING.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  metaLabel: {
    flex: 1,
    fontSize: 12,
    color: colors.textSecondary,
  },
  metaValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  startBtn: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    height: 50,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.primary,
  },
  startBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.white,
  },
  processingWrapper: {
    marginTop: SPACING.xxl,
    marginHorizontal: SPACING.xl,
    alignItems: 'center',
    padding: SPACING.xl,
  },
  processingSpinnerRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 6,
    borderColor: '#DBEAFE',
    borderTopColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  processingPercentText: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.primary,
  },
  processingTitle: {
    marginTop: SPACING.lg,
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  processingTrack: {
    marginTop: SPACING.lg,
    width: '100%',
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E2E8F0',
    overflow: 'hidden',
  },
  processingFill: {
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  processingHint: {
    marginTop: SPACING.md,
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  doneIconWrapper: {
    marginTop: SPACING.xxl,
    alignSelf: 'center',
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DCFCE7',
  },
  doneTitle: {
    marginTop: SPACING.lg,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  doneSubtitle: {
    marginTop: 4,
    textAlign: 'center',
    fontSize: 13,
    color: colors.textSecondary,
    marginHorizontal: SPACING.xl,
  },
  actionsRow: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  primaryActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    height: 48,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.primary,
  },
  primaryActionBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.white,
  },
  outlineActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    height: 48,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.white,
  },
  outlineActionBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  shareSectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  shareSectionTitleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  shareSectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  shareSectionCountText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
  },
  shareSectionHint: {
    marginTop: 2,
    fontSize: 11,
    color: colors.textSecondary,
  },
  searchInputWrapper: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    height: 40,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: RADIUS.sm,
    paddingHorizontal: SPACING.md,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: colors.textPrimary,
    padding: 0,
  },
  pickerListWrapper: {
    marginTop: SPACING.sm,
    maxHeight: 220,
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  pickerCheckbox: {
    width: 20,
    height: 20,
    borderRadius: RADIUS.xs,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerCheckboxSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  pickerAvatarWrapper: {
    width: 32,
    height: 32,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  pickerInfo: {
    flex: 1,
    flexShrink: 1,
  },
  pickerName: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  pickerMeta: {
    marginTop: 1,
    fontSize: 11,
    color: colors.textSecondary,
  },
  pickerStateWrapper: {
    marginTop: SPACING.md,
    alignItems: 'center',
    paddingVertical: SPACING.lg,
  },
  pickerStateText: {
    marginTop: SPACING.sm,
    fontSize: 12,
    color: colors.textSecondary,
  },
  shareSendBtn: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    height: 46,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.primary,
  },
  shareSendBtnDisabled: {
    backgroundColor: '#CBD5E1',
  },
  shareSendBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.white,
  },
  sectionDivider: {
    marginVertical: SPACING.lg,
    marginHorizontal: SPACING.xl,
    height: 1,
    backgroundColor: colors.border,
  },
  footerLinksRow: {
    marginTop: SPACING.xl,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: SPACING.lg,
  },
  footerLinkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  footerLinkText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
});
