import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxl,
    borderBottomLeftRadius: RADIUS.xxl,
    borderBottomRightRadius: RADIUS.xxl,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '700',
    color: colors.white,
  },
  heroCard: {
    marginTop: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    overflow: 'hidden',
  },
  heroTitle: {
    fontSize: 19,
    fontWeight: '800',
    color: colors.white,
    lineHeight: 25,
    paddingRight: 70,
  },
  heroDesc: {
    marginTop: SPACING.sm,
    fontSize: 12,
    lineHeight: 17,
    color: 'rgba(255,255,255,0.85)',
    paddingRight: 70,
  },
  heroDecorIcon: {
    position: 'absolute',
    right: -10,
    bottom: -10,
  },
  statsCard: {
    marginTop: SPACING.xl,
    flexDirection: 'row',
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
    gap: SPACING.xs,
  },
  statIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
    textAlign: 'center',
  },
  statLabelActive: {
    color: colors.primary,
  },
  statValue: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  toolbarRow: {
    marginTop: SPACING.xl,
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  searchInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    height: 46,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.white,
    paddingHorizontal: SPACING.md,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: colors.textPrimary,
    padding: 0,
  },
  filterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    height: 46,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  filterBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  monthTitle: {
    marginTop: SPACING.xl,
    marginBottom: SPACING.sm,
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  invoiceCard: {
    marginBottom: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  invoiceIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  invoiceInfo: {
    flex: 1,
  },
  invoiceTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  invoiceCode: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textSecondary,
  },
  invoiceDateRow: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  invoiceDate: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  invoiceRightCol: {
    alignItems: 'flex-end',
    gap: SPACING.xs,
  },
  invoiceStatus: {
    fontSize: 12,
    fontWeight: '700',
  },
  invoiceAmount: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  downloadBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  loadingWrapper: {
    paddingVertical: SPACING.xxl,
  },
  emptyWrapper: {
    alignItems: 'center',
    paddingVertical: SPACING.xxl,
  },
  emptyIconWrapper: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
    marginBottom: SPACING.md,
  },
  emptyTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  emptyDesc: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textSecondary,
  },
  supportBanner: {
    marginTop: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: '#EEF7FF',
  },
  supportIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  supportTextWrapper: {
    flex: 1,
  },
  supportTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  supportDesc: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 17,
    color: colors.textSecondary,
  },
  supportBtn: {
    marginTop: SPACING.md,
    alignSelf: 'flex-start',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.xs,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.white,
  },
  supportBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
});
