import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxxl + SPACING.md,
    borderBottomLeftRadius: RADIUS.xxl,
    borderBottomRightRadius: RADIUS.xxl,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerRightRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '700',
    color: colors.white,
  },
  cartBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    paddingHorizontal: 3,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DC2626',
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  cartBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: colors.white,
  },
  imageCard: {
    marginTop: -SPACING.xxxl,
    marginHorizontal: SPACING.xl,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
    overflow: 'hidden',
  },
  imageWrapper: {
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoCard: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
  },
  categoryBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: SPACING.md,
    paddingVertical: 4,
    borderRadius: RADIUS.xs,
  },
  categoryBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.white,
  },
  nameRow: {
    marginTop: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: SPACING.sm,
  },
  productName: {
    flex: 1,
    fontSize: 20,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  favoriteBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  productSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: colors.textSecondary,
  },
  metaRow: {
    marginTop: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  ratingText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  reviewCountText: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  metaDivider: {
    width: 1,
    height: 12,
    backgroundColor: colors.border,
  },
  soldText: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  priceRow: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  price: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.primary,
  },
  originalPrice: {
    fontSize: 14,
    color: colors.textSecondary,
    textDecorationLine: 'line-through',
  },
  discountBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
    backgroundColor: '#FEE2E2',
  },
  discountBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#DC2626',
  },
  specsGrid: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: '#EEF7FF',
  },
  specItem: {
    flexBasis: '47%',
    flexGrow: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  specLabel: {
    fontSize: 10,
    color: colors.textSecondary,
  },
  specValue: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  sectionCard: {
    marginTop: SPACING.xl,
    marginHorizontal: SPACING.xl,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  sectionLinkText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  descriptionText: {
    marginTop: SPACING.sm,
    fontSize: 13,
    lineHeight: 20,
    color: colors.textSecondary,
  },
  highlightsGrid: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  highlightCard: {
    flexBasis: '47%',
    flexGrow: 1,
    alignItems: 'center',
    gap: SPACING.xs,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
  },
  highlightIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  highlightLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  relatedList: {
    marginTop: SPACING.md,
    gap: SPACING.md,
  },
  relatedCard: {
    width: 128,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    ...SHADOW.card,
  },
  relatedImageWrapper: {
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  relatedInfo: {
    padding: SPACING.sm,
  },
  relatedName: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  relatedSubtitle: {
    marginTop: 1,
    fontSize: 9,
    color: colors.textSecondary,
  },
  relatedPriceRow: {
    marginTop: SPACING.xs,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  relatedPrice: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.primary,
  },
  addToCartBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  bottomBar: {
    flexDirection: 'row',
    gap: SPACING.sm,
    paddingHorizontal: SPACING.xl,
    paddingVertical: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.white,
  },
  supportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    paddingHorizontal: SPACING.lg,
    height: 50,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#EEF7FF',
  },
  supportBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  addToCartMainBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    height: 50,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.primary,
  },
  addToCartMainBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.white,
  },
  notFoundWrapper: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.md,
  },
  notFoundText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
});
