import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    paddingHorizontal: SPACING.xl,
    paddingTop: SPACING.xl,
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxl,
    borderBottomLeftRadius: RADIUS.xxl,
    borderBottomRightRadius: RADIUS.xxl,
  },
  headerBackground: {
    ...StyleSheet.absoluteFillObject,
    width: undefined,
    height: undefined,
    opacity: 0.2,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.white,
  },
  headerLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerLinkText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.white,
  },
  balanceCard: {
    marginTop: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    overflow: 'hidden',
  },
  balanceTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  balanceLabel: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.85)',
  },
  balanceValue: {
    marginTop: SPACING.xs,
    fontSize: 30,
    fontWeight: '800',
    color: colors.white,
  },
  balanceLoading: {
    marginTop: SPACING.md,
    alignSelf: 'flex-start',
  },
  safeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    alignSelf: 'flex-start',
    marginTop: SPACING.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  safeBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.white,
  },
  balanceDecorIcon: {
    position: 'absolute',
    right: -8,
    bottom: -8,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: SPACING.sm,
  },
  amountInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 56,
    borderWidth: 1.5,
    borderColor: colors.primary,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.white,
    paddingHorizontal: SPACING.lg,
  },
  amountCurrency: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primary,
    marginRight: SPACING.sm,
  },
  amountInput: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
    padding: 0,
  },
  amountAllText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
    textDecorationLine: 'underline',
  },
  amountHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: SPACING.sm,
  },
  amountHintText: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  amountFeeText: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  amountFeeValue: {
    fontWeight: '700',
    color: '#16A34A',
  },
  quickAddRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
    marginTop: SPACING.md,
  },
  quickAddChip: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: 999,
    backgroundColor: '#EEF7FF',
  },
  quickAddChipActive: {
    backgroundColor: colors.primary,
  },
  quickAddChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.primary,
  },
  quickAddChipTextActive: {
    color: colors.white,
  },
  bankCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    padding: SPACING.md,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  bankIcon: {
    width: 44,
    height: 44,
    borderRadius: RADIUS.xs,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  bankInfo: {
    flex: 1,
  },
  bankName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  bankNumber: {
    marginTop: 2,
    fontSize: 13,
    color: colors.textSecondary,
  },
  bankOwner: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textSecondary,
  },
  bankChangeBtn: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.xs,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  bankChangeBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  noteInputWrapper: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    minHeight: 56,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.white,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    gap: SPACING.sm,
  },
  noteInput: {
    flex: 1,
    fontSize: 14,
    color: colors.textPrimary,
    padding: 0,
    minHeight: 24,
  },
  noteCounter: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  infoBanner: {
    flexDirection: 'row',
    gap: SPACING.md,
    marginTop: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.md,
    backgroundColor: '#EEF7FF',
  },
  infoIconWrapper: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  infoTextWrapper: {
    flex: 1,
  },
  infoTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  infoBullet: {
    marginTop: SPACING.xs,
    fontSize: 12,
    lineHeight: 18,
    color: colors.textSecondary,
  },
  summaryCard: {
    marginTop: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    ...SHADOW.card,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: SPACING.xs,
  },
  summaryLabel: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  summaryValue: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  summaryValueGreen: {
    color: '#16A34A',
  },
  summaryDivider: {
    height: 1,
    backgroundColor: '#F1F5F9',
    marginVertical: SPACING.sm,
  },
  summaryNetLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  summaryNetValue: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.primary,
  },
  error: {
    marginTop: SPACING.xs,
    fontSize: 12,
    color: colors.error,
  },
  bottomBar: {
    paddingHorizontal: SPACING.xl,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.xl,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    ...SHADOW.card,
  },
  submitButton: {
    height: 52,
    justifyContent: 'center',
    borderRadius: RADIUS.sm,
    backgroundColor: colors.primary,
  },
  submitButtonDisabled: {
    opacity: 0.5,
  },
});
