import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  content: {
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxxl + SPACING.lg,
    borderBottomLeftRadius: RADIUS.xxl,
    borderBottomRightRadius: RADIUS.xxl,
  },
  headerBackground: {
    ...StyleSheet.absoluteFillObject,
    width: undefined,
    height: undefined,
    opacity: 0.2,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.white,
  },
  headerLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  headerLinkText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.white,
  },
  balanceCard: {
    marginTop: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    overflow: 'hidden',
  },
  balanceTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  balanceLabel: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.85)',
  },
  balanceValue: {
    marginTop: SPACING.xs,
    fontSize: 30,
    fontWeight: '800',
    color: colors.white,
  },
  balanceLoading: {
    marginTop: SPACING.md,
    alignSelf: 'flex-start',
  },
  availableLabel: {
    marginTop: SPACING.lg,
    fontSize: 12,
    color: 'rgba(255,255,255,0.75)',
  },
  availableValue: {
    marginTop: 2,
    fontSize: 16,
    fontWeight: '700',
    color: colors.white,
  },
  balanceDecorIcon: {
    position: 'absolute',
    right: -8,
    bottom: -8,
  },
  quickActionsCard: {
    marginHorizontal: SPACING.xl,
    marginTop: -SPACING.xxxl,
    backgroundColor: colors.white,
    borderRadius: RADIUS.lg,
    paddingVertical: SPACING.lg,
    ...SHADOW.card,
  },
  quickActionsRow: {
    flexDirection: 'row',
  },
  quickActionsRowSecond: {
    marginTop: SPACING.lg,
    paddingTop: SPACING.lg,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  quickAction: {
    flex: 1,
    alignItems: 'center',
    gap: SPACING.xs,
  },
  quickActionIcon: {
    width: 44,
    height: 44,
    borderRadius: RADIUS.xs,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  quickActionLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  securityBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    marginHorizontal: SPACING.xl,
    marginTop: SPACING.lg,
    padding: SPACING.lg,
    borderRadius: RADIUS.md,
    backgroundColor: '#EEF7FF',
  },
  securityIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  securityTextWrapper: {
    flex: 1,
  },
  securityTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  securityDesc: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textSecondary,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: SPACING.xl,
    marginTop: SPACING.xxl,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  seeAllText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.primary,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.xs,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  statsCard: {
    flexDirection: 'row',
    marginHorizontal: SPACING.xl,
    marginTop: SPACING.md,
    backgroundColor: colors.white,
    borderRadius: RADIUS.lg,
    paddingVertical: SPACING.lg,
    ...SHADOW.card,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statBorder: {
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: colors.border,
  },
  statLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  statValue: {
    marginTop: SPACING.xs,
    fontSize: 16,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  transactionsCard: {
    marginHorizontal: SPACING.xl,
    marginTop: SPACING.md,
    backgroundColor: colors.white,
    borderRadius: RADIUS.lg,
    paddingHorizontal: SPACING.lg,
    ...SHADOW.card,
  },
  transactionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  transactionRowLast: {
    borderBottomWidth: 0,
  },
  transactionIcon: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.xs,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transactionInfo: {
    flex: 1,
  },
  transactionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  transactionSubtitle: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textSecondary,
  },
  transactionAmountWrapper: {
    alignItems: 'flex-end',
  },
  transactionAmount: {
    fontSize: 14,
    fontWeight: '700',
  },
  transactionDate: {
    marginTop: 2,
    fontSize: 11,
    color: colors.textSecondary,
  },
  emptyText: {
    paddingVertical: SPACING.xxl,
    textAlign: 'center',
    fontSize: 13,
    color: colors.textSecondary,
  },
  loadingWrapper: {
    paddingVertical: SPACING.xxl,
  },
  referralBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    marginHorizontal: SPACING.xl,
    marginTop: SPACING.xxl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: '#EEF7FF',
  },
  referralIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: RADIUS.xs,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  referralText: {
    flex: 1,
  },
  referralTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  referralDesc: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textSecondary,
  },
  referralBtn: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.xs,
    backgroundColor: colors.primary,
  },
  referralBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.white,
  },
});
