import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    paddingBottom: SPACING.xxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxxl,
    borderBottomLeftRadius: RADIUS.xxl,
    borderBottomRightRadius: RADIUS.xxl,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: colors.white,
  },
  headerRightRow: {
    flexDirection: 'row',
    gap: SPACING.lg,
  },
  headerActionBtn: {
    alignItems: 'center',
    gap: 2,
  },
  headerActionBtnText: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.white,
  },
  infoCard: {
    marginTop: -SPACING.xxl,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  infoImageWrapper: {
    width: 76,
    height: 96,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoCol: {
    flex: 1,
    marginLeft: SPACING.md,
  },
  infoName: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  infoCategoryBadge: {
    marginTop: 4,
    alignSelf: 'flex-start',
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
  },
  infoCategoryBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  infoMetaText: {
    marginTop: SPACING.sm,
    fontSize: 11,
    color: colors.textSecondary,
  },
  progressRow: {
    marginTop: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  progressLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  progressTrack: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#E2E8F0',
    overflow: 'hidden',
  },
  progressFill: {
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
  },
  progressPercent: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
  },
  tabsRow: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabItemActive: {
    borderBottomColor: colors.primary,
  },
  tabItemText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  tabItemTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  viewerToolbarRow: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  viewerToolbarBtn: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
  },
  pageNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  pageNavBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  pageNavBtnDisabled: {
    opacity: 0.4,
  },
  pageNavText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  pageViewerWrapper: {
    marginTop: SPACING.md,
    marginHorizontal: SPACING.xl,
  },
  pageViewerCard: {
    height: 360,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
    padding: SPACING.xl,
    ...SHADOW.card,
  },
  pageViewerCardDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
  pageMockLine: {
    height: 10,
    borderRadius: 5,
    backgroundColor: '#E2E8F0',
    marginTop: SPACING.md,
  },
  pageMockLineDark: {
    backgroundColor: '#334155',
  },
  pageNumberBadge: {
    position: 'absolute',
    bottom: SPACING.md,
    left: SPACING.md,
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  pageNumberBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.white,
  },
  pageArrowBtn: {
    position: 'absolute',
    top: '50%',
    marginTop: -18,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  pageArrowBtnLeft: {
    left: -SPACING.md,
  },
  pageArrowBtnRight: {
    right: -SPACING.md,
  },
  thumbStrip: {
    marginTop: SPACING.md,
    paddingHorizontal: SPACING.xl,
    gap: SPACING.sm,
  },
  thumbItem: {
    width: 52,
    alignItems: 'center',
    gap: 4,
  },
  thumbBox: {
    width: 52,
    height: 68,
    borderRadius: RADIUS.xs,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  thumbBoxActive: {
    borderColor: colors.primary,
  },
  thumbNumber: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  thumbNumberActive: {
    color: colors.primary,
  },
  panelWrapper: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
  },
  tocRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: SPACING.sm,
  },
  tocRowTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  noteAddCard: {
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: SPACING.md,
  },
  noteAddLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  noteInput: {
    marginTop: SPACING.sm,
    minHeight: 60,
    fontSize: 13,
    color: colors.textPrimary,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: RADIUS.sm,
    padding: SPACING.sm,
  },
  noteSaveBtn: {
    marginTop: SPACING.sm,
    alignSelf: 'flex-end',
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.primary,
  },
  noteSaveBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.white,
  },
  noteCard: {
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: SPACING.sm,
  },
  noteCardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  notePageTag: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
  },
  noteTime: {
    fontSize: 10,
    color: colors.textSecondary,
  },
  noteText: {
    marginTop: 4,
    fontSize: 13,
    color: colors.textPrimary,
  },
  resourceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: SPACING.sm,
  },
  resourceIconWrapper: {
    width: 38,
    height: 38,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  resourceInfo: {
    flex: 1,
  },
  resourceName: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  resourceMeta: {
    marginTop: 1,
    fontSize: 11,
    color: colors.textSecondary,
  },
  resourceDownloadBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  emptyWrapper: {
    alignItems: 'center',
    paddingVertical: SPACING.xxl,
    gap: SPACING.sm,
  },
  emptyText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  bottomToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: SPACING.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.white,
  },
  bottomToolbarBtn: {
    alignItems: 'center',
    gap: 3,
    minWidth: 56,
  },
  bottomToolbarText: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  bottomToolbarCenterBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  notFoundWrapper: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.md,
  },
  notFoundText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
});
