import { StudentAttendance } from './types';

export const ATTENDANCE_DATA: StudentAttendance[] = [
  {
    id: '1',
    no: '01',
    fullName: 'Nguyễn Minh Anh',
    avatar: 'https://i.pravatar.cc/150?img=12',
    status: 'present',
    checkInTime: '08:05',
  },
  {
    id: '2',
    no: '02',
    fullName: 'Trần Bảo Châu',
    avatar: 'https://i.pravatar.cc/150?img=32',
    status: 'present',
    checkInTime: '08:06',
  },
  {
    id: '3',
    no: '03',
    fullName: 'Lê Gia Huy',
    avatar: 'https://i.pravatar.cc/150?img=15',
    status: 'present',
    checkInTime: '08:07',
  },
  {
    id: '4',
    no: '04',
    fullName: 'Phạm Khánh Linh',
    avatar: 'https://i.pravatar.cc/150?img=44',
    status: 'present',
    checkInTime: '08:08',
  },
  {
    id: '5',
    no: '05',
    fullName: 'Hoàng Đức Mạnh',
    avatar: 'https://i.pravatar.cc/150?img=18',
    status: 'late',
    checkInTime: '08:15',
  },
  {
    id: '6',
    no: '06',
    fullName: 'Vũ Quỳnh Anh',
    avatar: 'https://i.pravatar.cc/150?img=47',
    status: 'late',
    checkInTime: '08:18',
  },
  {
    id: '7',
    no: '07',
    fullName: 'Đỗ Thành Nam',
    avatar: 'https://i.pravatar.cc/150?img=25',
    status: 'absent',
  },
  {
    id: '8',
    no: '08',
    fullName: 'Bùi Ngọc Diệp',
    avatar: 'https://i.pravatar.cc/150?img=49',
    status: 'absent',
  },
  {
    id: '9',
    no: '09',
    fullName: 'Nguyễn Hoàng Phúc',
    avatar: 'https://i.pravatar.cc/150?img=20',
    status: 'present',
    checkInTime: '08:04',
  },
  {
    id: '10',
    no: '10',
    fullName: 'Trần Gia Bảo',
    avatar: 'https://i.pravatar.cc/150?img=11',
    status: 'present',
    checkInTime: '08:03',
  },
  {
    id: '11',
    no: '11',
    fullName: 'Lê Minh Khang',
    avatar: 'https://i.pravatar.cc/150?img=14',
    status: 'present',
    checkInTime: '08:06',
  },
  {
    id: '12',
    no: '12',
    fullName: 'Phạm Tuệ Nhi',
    avatar: 'https://i.pravatar.cc/150?img=48',
    status: 'present',
    checkInTime: '08:07',
  },
  {
    id: '13',
    no: '13',
    fullName: 'Võ Nhật Minh',
    avatar: 'https://i.pravatar.cc/150?img=22',
    status: 'present',
    checkInTime: '08:05',
  },
  {
    id: '14',
    no: '14',
    fullName: 'Ngô Hải Đăng',
    avatar: 'https://i.pravatar.cc/150?img=17',
    status: 'present',
    checkInTime: '08:08',
  },
  {
    id: '15',
    no: '15',
    fullName: 'Đặng Phương Anh',
    avatar: 'https://i.pravatar.cc/150?img=50',
    status: 'present',
    checkInTime: '08:02',
  },
  {
    id: '16',
    no: '16',
    fullName: 'Trương Anh Thư',
    avatar: 'https://i.pravatar.cc/150?img=45',
    status: 'present',
    checkInTime: '08:04',
  },
  {
    id: '17',
    no: '17',
    fullName: 'Lý Gia Hân',
    avatar: 'https://i.pravatar.cc/150?img=46',
    status: 'present',
    checkInTime: '08:06',
  },
  {
    id: '18',
    no: '18',
    fullName: 'Nguyễn Quốc Bảo',
    avatar: 'https://i.pravatar.cc/150?img=16',
    status: 'present',
    checkInTime: '08:05',
  },
  {
    id: '19',
    no: '19',
    fullName: 'Phan Minh Đức',
    avatar: 'https://i.pravatar.cc/150?img=21',
    status: 'present',
    checkInTime: '08:09',
  },
  {
    id: '20',
    no: '20',
    fullName: 'Lê Thanh Trúc',
    avatar: 'https://i.pravatar.cc/150?img=43',
    status: 'present',
    checkInTime: '08:07',
  },
  {
    id: '21',
    no: '21',
    fullName: 'Trần Khôi Nguyên',
    avatar: 'https://i.pravatar.cc/150?img=24',
    status: 'unmarked',
  },
  {
    id: '22',
    no: '22',
    fullName: 'Nguyễn Thảo Vy',
    avatar: 'https://i.pravatar.cc/150?img=42',
    status: 'unmarked',
  },
];