import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    padding: SPACING.xl,
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.lg,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: colors.white,
  },
  toolbarRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  toolbarBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    height: 42,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  toolbarBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  overviewCard: {
    marginTop: SPACING.lg,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.primary,
  },
  overviewHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  overviewTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.white,
  },
  overviewCompareBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.xs,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  overviewCompareText: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.white,
  },
  overviewStatsRow: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: SPACING.lg,
  },
  overviewStatItem: {
    width: '50%',
    alignItems: 'center',
    gap: 4,
  },
  overviewStatIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  overviewStatLabel: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.8)',
  },
  overviewStatValue: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.white,
  },
  overviewGrowthRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  overviewGrowthText: {
    fontSize: 10,
    fontWeight: '700',
  },
  chartCard: {
    marginTop: SPACING.lg,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  chartTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  chartLegendRow: {
    marginTop: SPACING.sm,
    flexDirection: 'row',
    gap: SPACING.lg,
  },
  chartLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  chartLegendLine: {
    width: 14,
    height: 2,
    borderRadius: 1,
  },
  chartLegendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  chartLegendText: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  trendLabelsRow: {
    marginTop: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 34,
  },
  trendLabelText: {
    fontSize: 9,
    color: colors.textSecondary,
  },
  donutRow: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xl,
  },
  donutWrapper: {
    width: 96,
    height: 96,
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutCenterLabel: {
    position: 'absolute',
    alignItems: 'center',
  },
  donutCenterPct: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  donutCenterCaption: {
    fontSize: 9,
    color: colors.textSecondary,
  },
  donutLegend: {
    flex: 1,
    gap: SPACING.sm,
  },
  bucketRow: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  bucketCard: {
    flexBasis: '48%',
    flexGrow: 1,
    alignItems: 'center',
    gap: 4,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  bucketIconWrapper: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bucketLabel: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  bucketValue: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  sectionCard: {
    marginTop: SPACING.lg,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  sectionLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  sectionLinkText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  classRow: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    paddingTop: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  classIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  classInfo: {
    flex: 1.4,
  },
  className: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  classMeta: {
    marginTop: 1,
    fontSize: 11,
    color: colors.textSecondary,
  },
  classAmountCol: {
    flex: 1,
    alignItems: 'flex-end',
  },
  classAmountLabel: {
    fontSize: 9,
    color: colors.textSecondary,
  },
  classAmountValue: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  miniRingWrapper: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniRingLabel: {
    position: 'absolute',
  },
  miniRingText: {
    fontSize: 9,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  methodRow: {
    marginTop: SPACING.md,
  },
  methodHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  methodIconWrapper: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  methodLabel: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  methodAmount: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  methodPercent: {
    marginLeft: 6,
    fontSize: 11,
    color: colors.textSecondary,
  },
  methodBarTrack: {
    marginTop: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#F1F5F9',
    overflow: 'hidden',
  },
  methodBarFill: {
    height: 6,
    borderRadius: 3,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.5)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    padding: SPACING.xl,
    maxHeight: '70%',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: SPACING.md,
  },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  modalOptionText: {
    fontSize: 14,
    color: colors.textPrimary,
  },
  modalOptionTextActive: {
    fontWeight: '700',
    color: colors.primary,
  },
});
