import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxl,
    borderBottomLeftRadius: RADIUS.xxl,
    borderBottomRightRadius: RADIUS.xxl,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: colors.white,
  },
  notificationBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    minWidth: 15,
    height: 15,
    borderRadius: 8,
    paddingHorizontal: 3,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DC2626',
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  notificationBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: colors.white,
  },
  heroCard: {
    marginTop: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  heroInfo: {
    flex: 1,
  },
  heroLabel: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.85)',
  },
  heroValue: {
    marginTop: 4,
    fontSize: 24,
    fontWeight: '800',
    color: colors.white,
  },
  heroGrowthRow: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-start',
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  heroGrowthText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#BBF7D0',
  },
  heroIconWrapper: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  statsRow: {
    marginTop: -SPACING.xl,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  statCard: {
    flexBasis: '48%',
    flexGrow: 1,
    alignItems: 'center',
    gap: 4,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  statIconWrapper: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statValue: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  statLabel: {
    fontSize: 10,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  quickActionsCard: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    padding: SPACING.md,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  quickAction: {
    flex: 1,
    alignItems: 'center',
    gap: SPACING.xs,
  },
  quickActionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  quickActionLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  sectionCard: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  periodText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  donutRow: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xl,
  },
  donutChartWrapper: {
    width: 96,
    height: 96,
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutChartLabel: {
    position: 'absolute',
    alignItems: 'center',
  },
  donutChartPct: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  donutChartCaption: {
    fontSize: 9,
    color: colors.textSecondary,
  },
  legend: {
    flex: 1,
    gap: SPACING.sm,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: SPACING.sm,
  },
  legendLabel: {
    flex: 1,
    fontSize: 12,
    color: colors.textSecondary,
  },
  legendValue: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  reminderBanner: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: '#EEF7FF',
  },
  reminderIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  reminderText: {
    flex: 1,
  },
  reminderTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  reminderDesc: {
    marginTop: 2,
    fontSize: 11,
    lineHeight: 15,
    color: colors.textSecondary,
  },
  reminderBtn: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.xs,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.white,
  },
  reminderBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
  },
  toolbarRow: {
    marginTop: SPACING.xl,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  searchInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    height: 46,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.white,
    paddingHorizontal: SPACING.md,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: colors.textPrimary,
    padding: 0,
  },
  filterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    height: 46,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  filterBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  mainTabRow: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    padding: 4,
    borderRadius: RADIUS.md,
    backgroundColor: '#E9EEF6',
  },
  mainTabItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.sm,
  },
  mainTabItemActive: {
    backgroundColor: colors.white,
    ...SHADOW.card,
  },
  mainTabText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  mainTabTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  statusChipsRow: {
    marginTop: SPACING.md,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  statusChip: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  statusChipActive: {
    borderColor: colors.primary,
    backgroundColor: '#EEF7FF',
  },
  statusChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  statusChipTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  listWrapper: {
    marginTop: SPACING.md,
    marginHorizontal: SPACING.xl,
  },
  classCard: {
    marginBottom: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  classIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  classInfo: {
    flex: 1,
  },
  className: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  classMeta: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textSecondary,
  },
  classAmountCol: {
    alignItems: 'flex-end',
    gap: 2,
  },
  classAmountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  classAmountLabel: {
    fontSize: 10,
    color: colors.textSecondary,
  },
  classAmountValue: {
    fontSize: 11,
    fontWeight: '700',
  },
  studentCard: {
    marginBottom: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  studentAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  studentInfo: {
    flex: 1,
  },
  studentName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  studentMeta: {
    marginTop: 2,
    fontSize: 11,
    color: colors.textSecondary,
  },
  studentRightCol: {
    alignItems: 'flex-end',
    gap: 2,
  },
  studentStatusBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 1,
    borderRadius: RADIUS.xs,
  },
  studentStatusText: {
    fontSize: 10,
    fontWeight: '700',
  },
  studentAmount: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  studentDate: {
    fontSize: 10,
    color: colors.textSecondary,
  },
  emptyWrapper: {
    alignItems: 'center',
    paddingVertical: SPACING.xxl,
  },
  emptyText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
});
