import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    paddingBottom: SPACING.xxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxl,
    borderBottomLeftRadius: RADIUS.xxl,
    borderBottomRightRadius: RADIUS.xxl,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '700',
    color: colors.white,
  },
  headerRightRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  headerPreviewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  headerPreviewBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.white,
  },
  stepperCard: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  stepItem: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  stepDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E2E8F0',
  },
  stepDotActive: {
    backgroundColor: colors.primary,
  },
  stepDotDone: {
    backgroundColor: '#16A34A',
  },
  stepDotText: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.textSecondary,
  },
  stepDotTextActive: {
    color: colors.white,
  },
  stepLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSecondary,
    textAlign: 'center',
  },
  stepLabelActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  stepSeparator: {
    width: 12,
    marginTop: 11,
  },
  sectionCard: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  sectionCountText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
  fieldLabel: {
    marginTop: SPACING.lg,
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  fieldInputWrapper: {
    marginTop: SPACING.sm,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: RADIUS.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
  },
  fieldInput: {
    fontSize: 14,
    color: colors.textPrimary,
    padding: 0,
  },
  fieldTextarea: {
    fontSize: 14,
    color: colors.textPrimary,
    padding: 0,
    minHeight: 60,
    textAlignVertical: 'top',
  },
  fieldCounter: {
    marginTop: SPACING.xs,
    textAlign: 'right',
    fontSize: 11,
    color: colors.textSecondary,
  },
  questionCard: {
    marginTop: SPACING.md,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#F8FAFC',
  },
  questionTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  questionIndexBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  questionIndexBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.white,
  },
  questionIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  questionWordInfo: {
    flex: 1,
    flexShrink: 1,
  },
  questionWordName: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  questionWordMeaning: {
    marginTop: 1,
    fontSize: 11,
    color: colors.textSecondary,
  },
  questionAnswerTag: {
    marginTop: SPACING.md,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 5,
    borderRadius: RADIUS.xs,
    backgroundColor: '#DCFCE7',
  },
  questionAnswerTagText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#15803D',
  },
  questionSubLabel: {
    marginTop: SPACING.md,
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  distractorRow: {
    marginTop: SPACING.sm,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.xs,
  },
  distractorChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 5,
    borderRadius: RADIUS.xs,
    backgroundColor: '#FEE2E2',
  },
  distractorChipText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#B91C1C',
  },
  distractorAddChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 5,
    borderRadius: RADIUS.xs,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.primary,
  },
  distractorAddChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
  },
  hintInputWrapper: {
    marginTop: SPACING.sm,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: RADIUS.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    backgroundColor: colors.white,
  },
  hintInput: {
    fontSize: 12,
    color: colors.textPrimary,
    padding: 0,
  },
  mediaRow: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    gap: SPACING.lg,
  },
  mediaToggleCol: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  mediaToggleLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  mediaToggleLabelDisabled: {
    color: colors.textSecondary,
  },
  tipBox: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: '#EEF7FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  tipText: {
    flex: 1,
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 18,
  },
  tipTextBold: {
    fontWeight: '700',
    color: colors.primary,
  },
  bottomBar: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  bottomOutlineBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    height: 48,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.white,
  },
  bottomOutlineBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  bottomPrimaryBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    height: 48,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.primary,
  },
  bottomPrimaryBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.white,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.4)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    padding: SPACING.xl,
    maxHeight: '75%',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: SPACING.md,
  },
  modalOption: {
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalOptionText: {
    fontSize: 14,
    color: colors.textPrimary,
  },
});
