import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    padding: SPACING.xl,
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.lg,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '700',
    color: colors.white,
  },
  headerHelpBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  headerHelpText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.white,
  },
  stepperCard: {
    marginTop: -SPACING.md,
    marginHorizontal: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    ...SHADOW.card,
  },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stepCircleWrapper: {
    alignItems: 'center',
    width: 64,
  },
  stepCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1.5,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  stepLabel: {
    marginTop: SPACING.xs,
    fontSize: 11,
    fontWeight: '600',
    color: colors.primary,
    textAlign: 'center',
  },
  stepLine: {
    flex: 1,
    height: 2,
    backgroundColor: colors.primary,
    marginBottom: 18,
  },
  successWrapper: {
    marginTop: SPACING.xxl,
    alignItems: 'center',
  },
  successIconOuter: {
    width: 150,
    height: 150,
    borderRadius: 75,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,102,204,0.06)',
  },
  successIconInner: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    ...SHADOW.card,
  },
  confettiDot: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  successTitle: {
    marginTop: SPACING.xl,
    fontSize: 22,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  successDesc: {
    marginTop: SPACING.sm,
    fontSize: 13,
    lineHeight: 19,
    color: colors.textSecondary,
    textAlign: 'center',
    paddingHorizontal: SPACING.md,
  },
  sectionCard: {
    marginTop: SPACING.xxl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: SPACING.md,
  },
  orderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SPACING.md,
  },
  orderLabel: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  orderValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  orderMethodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  orderDivider: {
    marginVertical: SPACING.sm,
    height: 1,
    backgroundColor: '#F1F5F9',
  },
  orderAmountLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  orderAmountValue: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.primary,
  },
  featuresBanner: {
    marginTop: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: '#EEF7FF',
  },
  featuresTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
    textAlign: 'center',
  },
  featuresRow: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  featureItem: {
    width: '20%',
    alignItems: 'center',
    gap: SPACING.xs,
    marginBottom: SPACING.md,
  },
  featureIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  featureLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  supportBanner: {
    marginTop: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: '#DCFCE7',
  },
  supportIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  supportTextWrapper: {
    flex: 1,
  },
  supportTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#16A34A',
  },
  supportDesc: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textSecondary,
  },
  primaryBtn: {
    marginTop: SPACING.xl,
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.primary,
  },
  primaryBtnText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.white,
  },
  outlineBtn: {
    marginTop: SPACING.md,
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    borderRadius: RADIUS.sm,
    borderWidth: 1.5,
    borderColor: colors.primary,
    backgroundColor: colors.white,
  },
  outlineBtnText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primary,
  },
  guaranteeRow: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  guaranteeText: {
    fontSize: 11,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  loadingWrapper: {
    paddingVertical: SPACING.xxl,
  },
});
