import type { LibraryResource, RecentLibraryItem, StorageSegment } from "./_interface";

export const LIBRARY_RESOURCES: LibraryResource[] = [
  {
    id: "res-1",
    title: "Animals Vocabulary",
    type: "video",
    formatLabel: "Video",
    unit: "Unit 5",
    level: "Beginner",
    meta: "15 phút",
    views: 356,
    likes: 124,
    rating: 4.9,
    usageCount: 245,
    category: "Vocabulary",
    updatedAt: "15/05/2025 10:30",
    ownerName: "Cô Ngọc",
    gradient: "from-amber-200 to-orange-100",
  },
  {
    id: "res-2",
    title: "Starter Unit 5",
    type: "lesson_plan",
    formatLabel: "PDF",
    unit: "Unit 5",
    level: "Beginner",
    meta: "20 trang",
    views: 512,
    likes: 156,
    rating: 4.8,
    usageCount: 312,
    category: "Reading",
    updatedAt: "15/05/2025 09:15",
    ownerName: "Cô Ngọc",
    gradient: "from-sky-200 to-blue-100",
  },
  {
    id: "res-3",
    title: "Reading Practice",
    type: "worksheet",
    formatLabel: "DOCX",
    unit: "Unit 4",
    level: "Elementary",
    meta: "18 trang",
    views: 278,
    likes: 95,
    rating: 4.7,
    usageCount: 198,
    category: "Reading",
    updatedAt: "14/05/2025 16:45",
    ownerName: "Cô Minh",
    gradient: "from-emerald-200 to-teal-100",
  },
  {
    id: "res-4",
    title: "Family Members",
    type: "lesson_plan",
    formatLabel: "PPT",
    unit: "Unit 3",
    level: "Beginner",
    meta: "24 slide",
    views: 245,
    likes: 89,
    rating: 4.6,
    usageCount: 165,
    category: "Vocabulary",
    updatedAt: "13/05/2025 15:30",
    ownerName: "Cô Lan",
    gradient: "from-rose-200 to-pink-100",
  },
  {
    id: "res-5",
    title: "Numbers 1-20",
    type: "video",
    formatLabel: "Video",
    unit: "Unit 2",
    level: "Beginner",
    meta: "10 phút",
    views: 456,
    likes: 132,
    rating: 4.9,
    usageCount: 312,
    category: "Vocabulary",
    updatedAt: "13/05/2025 10:05",
    ownerName: "Cô Ngọc",
    gradient: "from-indigo-200 to-violet-100",
  },
  {
    id: "res-6",
    title: "Colors Worksheet",
    type: "worksheet",
    formatLabel: "PDF",
    unit: "Unit 1",
    level: "Beginner",
    meta: "12 trang",
    views: 320,
    likes: 101,
    rating: 4.8,
    usageCount: 241,
    category: "Vocabulary",
    updatedAt: "15/05/2025 11:05",
    ownerName: "Cô Ngọc",
    gradient: "from-yellow-200 to-lime-100",
  },
  {
    id: "res-7",
    title: "Animals Flashcard",
    type: "flashcard",
    formatLabel: "Flashcard",
    unit: "Unit 5",
    level: "Beginner",
    meta: "48 thẻ",
    views: 289,
    likes: 102,
    rating: 4.8,
    usageCount: 187,
    category: "Flashcard",
    updatedAt: "14/05/2025 11:05",
    ownerName: "Cô Ngọc",
    gradient: "from-pink-200 to-fuchsia-100",
  },
  {
    id: "res-8",
    title: "Alphabet Song",
    type: "audio",
    formatLabel: "Audio",
    unit: "Unit 1",
    level: "Beginner",
    meta: "3 phút",
    views: 198,
    likes: 76,
    rating: 4.7,
    usageCount: 143,
    category: "Listening",
    updatedAt: "14/05/2025 14:20",
    ownerName: "Cô Lan",
    gradient: "from-teal-200 to-cyan-100",
  },
  {
    id: "res-9",
    title: "Word Match Game",
    type: "game",
    formatLabel: "Game",
    unit: "Unit 2",
    level: "Beginner",
    meta: "10 câu",
    views: 234,
    likes: 88,
    rating: 4.9,
    usageCount: 176,
    category: "Game",
    updatedAt: "12/05/2025 09:40",
    ownerName: "Cô Minh",
    gradient: "from-violet-200 to-purple-100",
  },
  {
    id: "res-10",
    title: "Grammar Exercise",
    type: "worksheet",
    formatLabel: "DOCX",
    unit: "Unit 6",
    level: "Elementary",
    meta: "16 trang",
    views: 267,
    likes: 94,
    rating: 4.8,
    usageCount: 205,
    category: "Grammar",
    updatedAt: "15/05/2025 09:15",
    ownerName: "Cô Minh",
    gradient: "from-blue-200 to-indigo-100",
  },
  {
    id: "res-11",
    title: "Listening Practice",
    type: "audio",
    formatLabel: "Audio",
    unit: "Unit 4",
    level: "Elementary",
    meta: "8 phút",
    views: 231,
    likes: 79,
    rating: 4.7,
    usageCount: 165,
    category: "Listening",
    updatedAt: "14/05/2025 16:45",
    ownerName: "Cô Ngọc",
    gradient: "from-cyan-200 to-sky-100",
  },
  {
    id: "res-12",
    title: "Starter Unit 6",
    type: "lesson_plan",
    formatLabel: "PDF",
    unit: "Unit 6",
    level: "Elementary",
    meta: "22 trang",
    views: 198,
    likes: 64,
    rating: 4.8,
    usageCount: 132,
    category: "Grammar",
    updatedAt: "15/05/2025 10:30",
    ownerName: "Cô Ngọc",
    gradient: "from-sky-200 to-indigo-100",
  },
  {
    id: "res-13",
    title: "A Day with My Pet",
    type: "comic",
    formatLabel: "Truyện tranh",
    unit: "Unit 5",
    level: "Beginner",
    meta: "5 khung",
    views: 176,
    likes: 68,
    rating: 4.9,
    usageCount: 121,
    category: "Vocabulary",
    updatedAt: "16/05/2025 08:20",
    ownerName: "Cô Ngọc",
    gradient: "from-lime-200 to-emerald-100",
  },
  {
    id: "res-14",
    title: "At the Pet Shop - Hội thoại và từ vựng",
    type: "dialogue",
    formatLabel: "Hội thoại",
    unit: "Unit 5",
    level: "Beginner",
    meta: "02:30",
    views: 142,
    likes: 51,
    rating: 4.8,
    usageCount: 97,
    category: "Conversation",
    updatedAt: "16/05/2025 09:40",
    ownerName: "Cô Ngọc",
    gradient: "from-orange-200 to-amber-100",
  },
];

export const RECENT_LIBRARY_ITEMS: RecentLibraryItem[] = [
  { id: "res-12", title: "Starter Unit 6", type: "lesson_plan", updatedAt: "15/05/2025 10:30", ownerName: "Cô Ngọc" },
  { id: "res-10", title: "Grammar Exercise", type: "worksheet", updatedAt: "15/05/2025 09:15", ownerName: "Cô Minh" },
  { id: "res-11", title: "Listening Practice", type: "audio", updatedAt: "14/05/2025 16:45", ownerName: "Cô Ngọc" },
  { id: "res-8", title: "Alphabet Song", type: "audio", updatedAt: "14/05/2025 14:20", ownerName: "Cô Lan" },
  { id: "res-7", title: "Animals Flashcard", type: "flashcard", updatedAt: "14/05/2025 11:05", ownerName: "Cô Ngọc" },
];

export const STORAGE_SEGMENTS: StorageSegment[] = [
  { key: "video", label: "Video", color: "#0ea5e9", gb: 18.2 },
  { key: "pdf", label: "PDF", color: "#f43f5e", gb: 8.4 },
  { key: "audio", label: "Audio", color: "#f59e0b", gb: 4.6 },
  { key: "image", label: "Image", color: "#8b5cf6", gb: 2.1 },
  { key: "ppt", label: "PPT", color: "#10b981", gb: 1.3 },
];

export interface MostUsedRow {
  id: string;
  title: string;
  typeLabel: string;
  subject: string;
  usageCount: number;
  rating: number;
  updatedAt: string;
}

export const MOST_USED_ROWS: MostUsedRow[] = [
  { id: "mu-1", title: "Animals Vocabulary", typeLabel: "Video", subject: "Vocabulary", usageCount: 1245, rating: 4.9, updatedAt: "15/05/2025 10:30" },
  { id: "mu-2", title: "Starter Unit 5", typeLabel: "PDF", subject: "Reading", usageCount: 985, rating: 4.8, updatedAt: "15/05/2025 09:15" },
  { id: "mu-3", title: "Grammar Exercise", typeLabel: "Worksheet", subject: "Grammar", usageCount: 876, rating: 4.8, updatedAt: "14/05/2025 16:45" },
  { id: "mu-4", title: "Listening Practice", typeLabel: "Audio", subject: "Listening", usageCount: 765, rating: 4.7, updatedAt: "14/05/2025 14:20" },
  { id: "mu-5", title: "Flashcard Colors", typeLabel: "Flashcard", subject: "Vocabulary", usageCount: 654, rating: 4.9, updatedAt: "15/05/2025 11:05" },
];

export const LIBRARY_SUMMARY = {
  total: 486,
  totalDelta: 12,
  videoCount: 152,
  videoDelta: 8,
  worksheetCount: 198,
  worksheetDelta: 15,
  favoriteRate: 94,
  favoriteDelta: 6,
};
