import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.lg,
    borderBottomLeftRadius: RADIUS.xxl,
    borderBottomRightRadius: RADIUS.xxl,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '700',
    color: colors.white,
  },
  headerRightRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  cartBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    minWidth: 17,
    height: 17,
    borderRadius: 9,
    paddingHorizontal: 3,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DC2626',
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  cartBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.white,
  },
  searchRow: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  searchInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    height: 46,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.white,
    paddingHorizontal: SPACING.md,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: colors.textPrimary,
    padding: 0,
  },
  filterBtn: {
    width: 46,
    height: 46,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  bannerCard: {
    marginTop: SPACING.xl,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: '#1D4ED8',
    overflow: 'hidden',
  },
  bannerInfo: {
    flex: 1,
  },
  bannerEyebrow: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.85)',
  },
  bannerTitle: {
    marginTop: 2,
    fontSize: 17,
    fontWeight: '800',
    color: colors.white,
    lineHeight: 22,
  },
  bannerPill: {
    marginTop: SPACING.sm,
    alignSelf: 'flex-start',
    paddingHorizontal: SPACING.sm,
    paddingVertical: 3,
    borderRadius: RADIUS.xs,
    backgroundColor: '#FDE68A',
  },
  bannerPillText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#92400E',
  },
  bannerImage: {
    width: 72,
    height: 72,
    borderRadius: RADIUS.sm,
  },
  chipsRow: {
    marginTop: SPACING.lg,
    paddingHorizontal: SPACING.xl,
    gap: SPACING.sm,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  chipActive: {
    borderColor: colors.primary,
    backgroundColor: '#EEF7FF',
  },
  chipText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  chipTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  sectionHeaderRow: {
    marginTop: SPACING.xl,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  sectionLinkText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  productGrid: {
    marginTop: SPACING.md,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.md,
  },
  productCard: {
    flexBasis: '31%',
    flexGrow: 1,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    ...SHADOW.card,
  },
  productImageWrapper: {
    height: 84,
    alignItems: 'center',
    justifyContent: 'center',
  },
  productBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
  },
  productBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: colors.white,
  },
  productInfo: {
    padding: SPACING.sm,
  },
  productName: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  productSubtitle: {
    marginTop: 1,
    fontSize: 9,
    color: colors.textSecondary,
  },
  productPriceRow: {
    marginTop: SPACING.xs,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  productPriceCol: {
    flex: 1,
  },
  productPrice: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.primary,
  },
  productOriginalPrice: {
    fontSize: 9,
    color: colors.textSecondary,
    textDecorationLine: 'line-through',
  },
  addToCartBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  categoryGrid: {
    marginTop: SPACING.md,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.md,
  },
  categoryTile: {
    flexBasis: '47%',
    flexGrow: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
  },
  categoryTileIcon: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryTileInfo: {
    flex: 1,
  },
  categoryTileName: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  categoryTileCount: {
    marginTop: 1,
    fontSize: 11,
    color: colors.textSecondary,
  },
  bestsellerList: {
    marginTop: SPACING.md,
    paddingHorizontal: SPACING.xl,
    gap: SPACING.md,
  },
  bestsellerCard: {
    width: 128,
    borderRadius: RADIUS.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    ...SHADOW.card,
  },
  bestsellerImageWrapper: {
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rankBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
  },
  rankBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: colors.white,
  },
  bestsellerInfo: {
    padding: SPACING.sm,
  },
  bestsellerName: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  bestsellerPriceRow: {
    marginTop: SPACING.xs,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bestsellerPrice: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.primary,
  },
  emptyWrapper: {
    marginTop: SPACING.md,
    marginHorizontal: SPACING.xl,
    alignItems: 'center',
    paddingVertical: SPACING.xxl,
  },
  emptyText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
});
