import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    padding: SPACING.xl,
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.lg,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: colors.white,
  },
  headerLinkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  headerLinkText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.white,
  },
  sectionCard: {
    marginTop: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  sectionTitleIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.primary,
  },
  formRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 46,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  formRowLast: {
    borderBottomWidth: 0,
  },
  formLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  formRequired: {
    color: colors.error,
  },
  formValueBtn: {
    flex: 1,
    marginLeft: SPACING.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: SPACING.xs,
  },
  formValueText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'right',
  },
  formValuePlaceholder: {
    color: colors.textSecondary,
    fontWeight: '400',
  },
  formTextInput: {
    flex: 1,
    marginLeft: SPACING.lg,
    fontSize: 13,
    color: colors.textPrimary,
    textAlign: 'right',
    padding: 0,
  },
  formAmountSuffix: {
    marginLeft: 4,
    fontSize: 13,
    color: colors.textSecondary,
  },
  dateTimeWrapper: {
    flex: 1,
    marginLeft: SPACING.lg,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.md,
  },
  categoryCard: {
    width: '22.5%',
    aspectRatio: 0.95,
    borderRadius: RADIUS.sm,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.xs,
    paddingHorizontal: 4,
  },
  categoryCardActive: {
    borderColor: colors.primary,
    backgroundColor: '#F8FBFF',
  },
  categoryIcon: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.xs,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryLabel: {
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
    color: colors.textPrimary,
  },
  categoryCheckBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.white,
  },
  attachBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    padding: SPACING.md,
    borderRadius: RADIUS.sm,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: colors.border,
    backgroundColor: '#F8FAFC',
  },
  attachIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.xs,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF7FF',
  },
  attachInfo: {
    flex: 1,
  },
  attachTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  attachDesc: {
    marginTop: 2,
    fontSize: 11,
    color: colors.textSecondary,
  },
  noteInput: {
    minHeight: 70,
    fontSize: 13,
    color: colors.textPrimary,
    textAlignVertical: 'top',
    padding: 0,
  },
  noteCounter: {
    marginTop: SPACING.xs,
    textAlign: 'right',
    fontSize: 11,
    color: colors.textSecondary,
  },
  securityBanner: {
    marginTop: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.sm,
    backgroundColor: '#EEF7FF',
  },
  securityBannerText: {
    flex: 1,
    fontSize: 12,
    color: colors.textSecondary,
  },
  primaryBtn: {
    marginTop: SPACING.lg,
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.primary,
  },
  primaryBtnDisabled: {
    opacity: 0.5,
  },
  primaryBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.white,
  },
  outlineBtn: {
    marginTop: SPACING.md,
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    borderRadius: RADIUS.sm,
    borderWidth: 1.5,
    borderColor: colors.primary,
    backgroundColor: colors.white,
  },
  outlineBtnDisabled: {
    opacity: 0.5,
  },
  outlineBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.primary,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.5)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    padding: SPACING.xl,
    maxHeight: '75%',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: SPACING.md,
  },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  modalOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    flex: 1,
  },
  modalOptionText: {
    fontSize: 14,
    color: colors.textPrimary,
    flexShrink: 1,
  },
  modalOptionTextActive: {
    fontWeight: '700',
    color: colors.primary,
  },
  modalCustomInput: {
    marginTop: SPACING.md,
    height: 46,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: RADIUS.sm,
    paddingHorizontal: SPACING.md,
    fontSize: 14,
    color: colors.textPrimary,
  },
  modalCustomLabel: {
    marginTop: SPACING.lg,
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSecondary,
  },
});
