import { ClassInfo, StudentItem } from './types';

export const CLASS_INFO: ClassInfo = {
  id: '1',
  name: 'Starters 2A',
  ageGroup: 'Trẻ em',
  level: 'Beginner',
  room: 'Phòng 201',
  branch: 'Cơ sở 1',
  image: require('@tera/assets/app/element_84.png'),
  color: '#0B84FF',
  totalStudents: 24,
  presentCount: 22,
  absentCount: 2,
  attendanceRate: 91.7,
};

export const STUDENTS: StudentItem[] = [
  {
    id: '1',
    index: 1,
    name: 'Nguyễn Minh Khang',
    birthday: '12/04/2015',
    gender: 'Nam',
    rating: 4.8,
    tag: 'Tiến bộ tốt',
    tagColor: '#EEF9F0',
    tagTextColor: '#16A34A',
    status: 'present',
    attendanceRate: 95,
    avatar: require('@tera/assets/app/element_85.png'),
  },
  {
    id: '2',
    index: 2,
    name: 'Trần Bảo Châu',
    birthday: '25/06/2015',
    gender: 'Nữ',
    rating: 4.7,
    tag: 'Tích cực',
    tagColor: '#EEF5FF',
    tagTextColor: '#2D7DD2',
    status: 'present',
    attendanceRate: 92,
    avatar: require('@tera/assets/app/element_86.png'),
  },
  {
    id: '3',
    index: 3,
    name: 'Lê Hoàng Nam',
    birthday: '08/01/2015',
    gender: 'Nam',
    rating: 4.6,
    tag: 'Cần cố gắng',
    tagColor: '#FFF7E6',
    tagTextColor: '#D97706',
    status: 'present',
    attendanceRate: 88,
    avatar: require('@tera/assets/app/element_87.png'),
  },
  {
    id: '4',
    index: 4,
    name: 'Phạm Gia Hân',
    birthday: '17/09/2015',
    gender: 'Nữ',
    rating: 4.9,
    tag: 'Xuất sắc',
    tagColor: '#FFF0F5',
    tagTextColor: '#DB2777',
    status: 'absent',
    attendanceRate: 78,
    avatar: require('@tera/assets/app/element_88.png'),
  },
  {
    id: '5',
    index: 5,
    name: 'Đỗ Anh Khoa',
    birthday: '03/03/2015',
    gender: 'Nam',
    rating: 4.5,
    tag: 'Cần cố gắng',
    tagColor: '#FFF7E6',
    tagTextColor: '#D97706',
    status: 'absent',
    attendanceRate: 82,
    avatar: require('@tera/assets/app/element_89.png'),
  },
  {
    id: '6',
    index: 6,
    name: 'Võ Mai Anh',
    birthday: '21/11/2015',
    gender: 'Nữ',
    rating: 4.8,
    tag: 'Tiến bộ tốt',
    tagColor: '#EEF9F0',
    tagTextColor: '#16A34A',
    status: 'present',
    attendanceRate: 94,
    avatar: require('@tera/assets/app/element_90.png'),
  },
];
