import { StyleSheet } from 'react-native';

import colors, {
  RADIUS,
  SHADOW,
  SPACING,
} from '@tera/commons/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  flex: {
    flex: 1,
  },
  content: {
    paddingBottom: SPACING.xxxl,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxl,
    borderBottomLeftRadius: RADIUS.xxl,
    borderBottomRightRadius: RADIUS.xxl,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: colors.white,
  },
  headerRightRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
  },
  headerFilterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  headerFilterText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.white,
  },
  notificationBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    minWidth: 15,
    height: 15,
    borderRadius: 8,
    paddingHorizontal: 3,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DC2626',
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  notificationBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: colors.white,
  },
  statsCard: {
    marginTop: -SPACING.xl,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: SPACING.md,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  statItem: {
    flexBasis: '20%',
    alignItems: 'center',
    gap: 4,
  },
  statIconWrapper: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statValue: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  statLabel: {
    fontSize: 9,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  toolbarRow: {
    marginTop: SPACING.xl,
    marginHorizontal: SPACING.xl,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  searchInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    height: 46,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: RADIUS.sm,
    backgroundColor: colors.white,
    paddingHorizontal: SPACING.md,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: colors.textPrimary,
    padding: 0,
  },
  sortBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  sortBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
  chipsRow: {
    marginTop: SPACING.md,
    paddingHorizontal: SPACING.xl,
    gap: SPACING.sm,
  },
  chip: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  chipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  chipText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  chipTextActive: {
    color: colors.white,
    fontWeight: '700',
  },
  orderCard: {
    marginTop: SPACING.lg,
    marginHorizontal: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    ...SHADOW.card,
  },
  orderHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  orderCode: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  orderStatusBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
  },
  orderStatusText: {
    fontSize: 11,
    fontWeight: '700',
  },
  orderDate: {
    marginLeft: 'auto',
    fontSize: 11,
    color: colors.textSecondary,
  },
  moreBtn: {
    marginLeft: SPACING.xs,
    padding: 2,
  },
  customerRow: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  avatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.white,
  },
  customerInfo: {
    flex: 1,
  },
  customerName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  customerPhone: {
    marginTop: 1,
    fontSize: 12,
    color: colors.textSecondary,
  },
  customerAddressRow: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  customerAddress: {
    fontSize: 11,
    color: colors.textSecondary,
    flexShrink: 1,
  },
  orderMetaCol: {
    alignItems: 'flex-end',
  },
  itemCountText: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  orderTotal: {
    marginTop: 2,
    fontSize: 16,
    fontWeight: '800',
    color: colors.primary,
  },
  paymentBadge: {
    marginTop: 4,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
    backgroundColor: '#EEF7FF',
  },
  paymentBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.primary,
  },
  itemsRow: {
    marginTop: SPACING.md,
    gap: SPACING.sm,
  },
  itemThumb: {
    width: 108,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    padding: SPACING.xs,
    borderRadius: RADIUS.sm,
    backgroundColor: '#F8FAFC',
  },
  itemThumbIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.xs,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemThumbInfo: {
    flex: 1,
  },
  itemThumbName: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  itemThumbSubtitle: {
    fontSize: 9,
    color: colors.textSecondary,
  },
  itemThumbQty: {
    fontSize: 9,
    color: colors.textSecondary,
  },
  itemThumbPrice: {
    marginTop: 1,
    fontSize: 10,
    fontWeight: '700',
    color: colors.primary,
  },
  actionsRow: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    height: 42,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
  },
  actionBtnOutline: {
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  actionBtnDanger: {
    borderColor: '#FCA5A5',
    backgroundColor: colors.white,
  },
  actionBtnPrimary: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  actionBtnText: {
    fontSize: 12,
    fontWeight: '700',
  },
  trackingRow: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  trackingStepCol: {
    alignItems: 'center',
  },
  trackingDot: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trackingLine: {
    flex: 1,
    height: 2,
    marginTop: 12,
    borderTopWidth: 1.5,
    borderStyle: 'dashed',
  },
  trackingLabel: {
    marginTop: 4,
    fontSize: 10,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  trackingTime: {
    marginTop: 1,
    fontSize: 9,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  emptyWrapper: {
    marginTop: SPACING.xl,
    marginHorizontal: SPACING.xl,
    alignItems: 'center',
    paddingVertical: SPACING.xxl,
  },
  emptyText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
});
