import { ClassItem } from './types';

export const classes: ClassItem[] = [
  {
    id: '1',
    name: 'Starters 2A',
    level: 'Beginner',
    ageGroup: 'Trẻ em',
    room: 'Phòng 201',
    branch: 'Cơ sở 1',
    startTime: '08:00',
    endTime: '09:30',
    schedule: 'Thứ 3, 5, 7',
    students: 24,
    totalStudents: 24,
    color: '#0B84FF',
    image: require('@tera/assets/app/element_66.png'),
  },
  {
    id: '2',
    name: 'Movers 1B',
    level: 'Elementary',
    ageGroup: 'Trẻ em',
    room: 'Phòng 202',
    branch: 'Cơ sở 1',
    startTime: '09:45',
    endTime: '11:15',
    schedule: 'Thứ 3, 5, 7',
    students: 24,
    totalStudents: 24,
    color: '#14AE5C',
    image: require('@tera/assets/app/element_67.png'),
  },
  {
    id: '3',
    name: 'Flyers 3A',
    level: 'Pre-intermediate',
    ageGroup: 'Trẻ em',
    room: 'Phòng 203',
    branch: 'Cơ sở 1',
    startTime: '13:30',
    endTime: '15:00',
    schedule: 'Thứ 2, 4, 6',
    students: 24,
    totalStudents: 24,
    color: '#FF9900',
    image: require('@tera/assets/app/element_68.png'),
  },
];