import { appVersion } from '@tera/commons/constants/common';
import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
  version: appVersion,
  tables: [
    tableSchema({
      name: 'generals',
      columns: [
        { name: 'key', type: 'string', isIndexed: true },
        { name: 'value', type: 'string' },
        { name: 'version', type: 'number', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'table_version_logs',
      columns: [
        { name: 'table_name', type: 'string', isIndexed: true },
        { name: 'version', type: 'number', isIndexed: true },
        { name: 'is_dirty', type: 'number' },
        { name: 'last_sync_at', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'business_locations',
      columns: [
        { name: 'server_id', type: 'number', isIndexed: true },
        { name: 'version', type: 'number', isIndexed: true },
        { name: 'location_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'mobile', type: 'string' },
        { name: 'address', type: 'string' },
        { name: 'landmark', type: 'string' },
        { name: 'ward', type: 'string' },
        { name: 'state', type: 'string' },
        { name: 'city', type: 'string' },
        { name: 'country', type: 'string' },
        { name: 'is_default', type: 'number' },
        { name: 'is_new_address', type: 'number' },
        { name: 'is_delete', type: 'number', isIndexed: true },
        { name: 'is_dirty', type: 'number' },
        { name: 'last_sync_at', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sync_queues',
      columns: [
        { name: 'table_name', type: 'string', isIndexed: true },
        { name: 'record_id', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'action', type: 'string' },
        { name: 'payload', type: 'string' },
        { name: 'retries', type: 'number' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'customers',
      columns: [
        { name: 'server_id', type: 'number', isIndexed: true },
        { name: 'code', type: 'string', isIndexed: true },
        { name: 'business_name', type: 'string' },
        { name: 'phone', type: 'string', isIndexed: true },
        { name: 'avatar_url', type: 'string' },
        { name: 'email', type: 'string' },
        { name: 'address', type: 'string' },
        { name: 'tax', type: 'string' },
        { name: 'object', type: 'string' },
        { name: 'debt_limit', type: 'number' },
        { name: 'debt_period', type: 'number' },
        { name: 'is_delete', type: 'boolean' },
        { name: 'is_dirty', type: 'number' },
        { name: 'raw_data', type: 'string' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
